In [56]:
## 00. Pytorch fundamentals

In [57]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [58]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [59]:
print(torch.__version__)

1.13.1+cu116


In [60]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



## Introduction of tensor
### Creating tensors

In [61]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [62]:
scalar.ndim

0

In [63]:
scalar.item()

7

In [64]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [65]:
vector.ndim

1

In [66]:
vector.shape

torch.Size([2])

In [67]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [68]:
MATRIX.ndim

2

In [69]:
MATRIX.shape

torch.Size([2, 2])

In [70]:
MATRIX[0]

tensor([7, 8])

In [71]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [7, 8, 9]]])

In [72]:
TENSOR.ndim

3

In [73]:
TENSOR.shape

torch.Size([1, 3, 3])

In [74]:
TENSOR = torch.tensor([
                        [[1,2,3],
                        [3,4,5],
                        [7,8,9]],
                       [[1,2,3],
                        [3,4,5],
                        [7,8,9]]
                       ])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [7, 8, 9]],

        [[1, 2, 3],
         [3, 4, 5],
         [7, 8, 9]]])

In [75]:
TENSOR.ndim

3

In [76]:
TENSOR.shape

torch.Size([2, 3, 3])

# Random Tensors

In [77]:
# create a random tensor of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5709, 0.7954, 0.5113, 0.9418],
        [0.9840, 0.1536, 0.0327, 0.3741],
        [0.6476, 0.9848, 0.7929, 0.1089]])

In [78]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) # height, width, color

In [79]:
random_image_size_tensor.shape

torch.Size([3, 224, 224])

In [80]:
random_image_size_tensor.ndim

3

# Zeros and Ones

In [81]:

# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [82]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [83]:
ones.dtype

torch.float32

# Creating  a range of tensors and tensosrs-like

In [84]:
torch.arange(1,11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
one_to_ten = torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [87]:
five_shape_tensor = torch.arange(start=1,end=11,step=2)
five_shape_tensor

tensor([1, 3, 5, 7, 9])

In [88]:
five_ones = torch.ones_like(input=five_shape_tensor)
five_ones

tensor([1, 1, 1, 1, 1])

# Tensor Datatypes

**Note:** Tensor datatypes is one of the 3 big errors you will run into with PyTorch and Deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [89]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # what datatype is the tensor
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether or not the track gradients with this tensors operations
float_32_tensor.dtype

torch.float32

In [90]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [91]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)

In [92]:
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [93]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

# Getting information from tensors

1. tensor.dtype
2. tensor.shape
3. tensor.device

In [94]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6946, 0.9584, 0.8414, 0.0541],
        [0.5966, 0.8766, 0.4112, 0.2721],
        [0.8382, 0.7924, 0.8488, 0.4179]])

In [95]:
print(some_tensor)
print(f"Data Type: {some_tensor.dtype}")
print(f"Shape: {some_tensor.shape}")
print(f"Device: {some_tensor.device}")

tensor([[0.6946, 0.9584, 0.8414, 0.0541],
        [0.5966, 0.8766, 0.4112, 0.2721],
        [0.8382, 0.7924, 0.8488, 0.4179]])
Data Type: torch.float32
Shape: torch.Size([3, 4])
Device: cpu


# Manipulating Tensors

Tensor Operations:
* Addition
* Substraction
* Multiplication (element wise)
* division
* Matrix Multiplication

In [96]:
# Creating a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [97]:
tensor * 10

tensor([10, 20, 30])

In [98]:
tensor - 10

tensor([-9, -8, -7])

In [99]:
# Try out pyTorch in-built functions
torch.mul(tensor,5)

tensor([ 5, 10, 15])

In [100]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [101]:
tensor.ndim

1

# Matrix multiplication

Two main ways of performing multiplication in NN and DL

1. Element-wise multiplication
2. Matrix multiplication (dot product)

In [102]:
# Element wise
print(tensor,"*",tensor)
print(f"Answer: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Answer: tensor([1, 4, 9])


In [103]:
# Matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [104]:
# matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [105]:
%%time
value = 0 
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 232 µs, sys: 35 µs, total: 267 µs
Wall time: 277 µs


tensor(14)

In [106]:
%%time 
torch.matmul(tensor,tensor)

CPU times: user 89 µs, sys: 5 µs, total: 94 µs
Wall time: 99.2 µs


tensor(14)

# There are two main rules that performing matrix multiplication needs to satisfy:
1. The inner dimensions must match
2. The resulting matrix has the shape of the outer dimensions

In [107]:
torch.matmul(torch.rand(2,3),torch.rand(3,2)).shape

torch.Size([2, 2])

# One of the most common errors in deep learning (shape errors)

In [108]:
# shapes for matrix multiplication
tensor_A = torch.tensor([
    [1,2],
    [3,4],
    [5,6]
])

tensor_B = torch.tensor([
    [7,10],
    [8,11],
    [9,12]
])

#torch.mm(tensor_A,tensor_B) # torch.mm is the same as torch.matmul

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a transpose

In [109]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]), torch.Size([2, 3]))

In [110]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]), torch.Size([3, 2]))

In [111]:
torch.matmul(tensor_A,tensor_B.T).shape

torch.Size([3, 3])

In [112]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes:\ntensor_A = {tensor_A.shape}\ntensor_B = {tensor_B.shape}")
print(f"\nNew shapes:\ntensor_A = {tensor_A.shape}\ntensor_B.T = {tensor_B.T.shape}")
print(f"\nMultiplying: {tensor_A.shape} @ {tensor_B.shape} <--- inner dimension must match")

output = torch.mm(tensor_A,tensor_B.T)
print(f"\nOutput:\n{output}")

print(f"\nOutput shape: {output.shape}")

Original shapes:
tensor_A = torch.Size([3, 2])
tensor_B = torch.Size([3, 2])

New shapes:
tensor_A = torch.Size([3, 2])
tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) @ torch.Size([3, 2]) <--- inner dimension must match

Output:
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


# Finding the min, max, mean, sum, etc (aggregation)

In [113]:
# create a tensor
x = torch.arange(1,100,10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [114]:
# find the max 
torch.max(x), x.max()

(tensor(91), tensor(91))

In [115]:
# find the mean - note: the torch.mean() function requires a tensor of float32 dtype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [116]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

# Finding the Positional min/max

In [117]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [118]:
# Find the position in the tensor that has the minimum value with argmin() ---> it returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [119]:
x[0]

tensor(1)

In [120]:
# Find the position in the tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [121]:
x[9]

tensor(91)

# Reshaping, stacking, squeezing and unsqueezing

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - Combine multiple tensors on top of each other (vstack) or side by side (hstack) 
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [122]:
# Create a tensor
import torch
x = torch.arange(1,11)
x,x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [123]:
# Add an extra dimension
x_reshaped = x.reshape(5,2) # 5*2 = 10
x_reshaped,x_reshaped.shape

(tensor([[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8],
         [ 9, 10]]), torch.Size([5, 2]))

In [124]:
x = torch.arange(1,10)
x,x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [125]:
x_reshaped = x.reshape(1,9) # 1*9 = 9
x_reshaped,x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [126]:
# change the view
z = x.view(1,9)
z,z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [127]:
# changing z changes x (Because a view of a tensor shares the same memory as the original input)
z[:,0] = 5
z, x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [128]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [129]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [130]:
# torch.squeeze - removes all single dimensions from a target tensor
x_reshaped

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [131]:
x_reshaped.shape

torch.Size([1, 9])

In [132]:
x_reshaped.squeeze() # removes all of the 1 dimensions

tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])

In [133]:
x_reshaped.squeeze().shape

torch.Size([9])

In [134]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
New shape: torch.Size([9])


In [135]:
# torch.unsqueeze() - addes a single dim to a target tensor at a specific dim
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
Previous shape: torch.Size([9])

New tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
New shape: torch.Size([1, 9])


In [136]:
# torch.permute - rearranges the dimensions of the target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # [height,weidth,color]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour,height,weight]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [137]:
# view that returns the permuted shares the same memory as original
x_original[0,0,0] = 123
x_original[0,0,0], x_permuted[0,0,0]

(tensor(123.), tensor(123.))

# Indexing - Select data from tensors

Indexing with  Pytorch is similar to indexing with Numpy

In [138]:
# Creating a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [139]:
# let's index on out new tensor

x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [140]:
# index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [141]:
# index on last bracket
x[0][0][0]

tensor(1)

In [142]:
x[0][0][1]

tensor(2)

In [143]:
x[0][1][1]

tensor(5)

In [144]:
x[0][2][2]

tensor(9)

In [145]:
# use : to select all of a target dimention
x[:,0]

tensor([[1, 2, 3]])

In [146]:
# get all values of 0th and 1st dim but only index 1 of 2nd dim
x[:,:,1]

tensor([[2, 5, 8]])

In [147]:
# get all values of the 0 dim but only 1 index value of the 1st and 2nd dim
x[:,1,1]

tensor([5])

In [148]:
# get index 0 of 0th and 1st dim and all values of 2nd dim
x[0,0,:]

tensor([1, 2, 3])

In [150]:
x[0,2,2]

tensor(9)

In [155]:
x[0,:,2]

tensor([3, 6, 9])

# Pytorch tensors and Numpy

Numpy is a popular scientific python numerical computing library
because of this pytorch has functionality to interact with it.

* Data in Numpy, want in PyTorch tensor ---> `torch.from_numpy(ndarray`
* Pytorch tensor ---> NumPy ---> `torch.Tensor.numpy()`

In [176]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) #warning: when converting from numpy --> pytorch, pytorch reflects numpy's default datatype of float64 unless specefied otherwise 
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [177]:
torch.arange(1,8).dtype

torch.int64

In [178]:
array.dtype

dtype('float64')

In [179]:
tensor.dtype

torch.float64

In [180]:
# change the value of array, what will this do to tensor?
array = array+1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [181]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [183]:
tensor.dtype

dtype('float32')

In [184]:
numpy_tensor.dtype

dtype('float32')

In [185]:
# default dtype of tensor is float32
# default dtype of numpy is foloat64

In [186]:
# Change the tensor, what happens to numpy_tensor
tensor = tensor+1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducibility (trying to take the random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> do this again and again`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "falvour" the randomness

**Documentation:** https://pytorch.org/docs/stable/notes/randomness.html

In [188]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2577, 0.6955, 0.0608, 0.1808],
        [0.9732, 0.6047, 0.9898, 0.0386],
        [0.8036, 0.8275, 0.0188, 0.8326]])
tensor([[0.6627, 0.3221, 0.3924, 0.2674],
        [0.8424, 0.2923, 0.9067, 0.6843],
        [0.4854, 0.5887, 0.6988, 0.9485]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [191]:
# Let's make some random but reproducible tensors
import torch 

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers

Read: https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/

## 1. Getting a GPU

In [2]:
# Use Colab GPU: `Runtime ---> change runtime type ---> select GPU ---> save`
!nvidia-smi

Sun Feb  5 14:24:51 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   47C    P0    26W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## 2. Check for GPU access with PyTorch

In [3]:
# check for GPU access with pytorch
import torch
torch.cuda.is_available()

True

In [4]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [5]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/moels on the GPU is because using a GPU results in faster computations.

In [9]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3],device="cpu")

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [11]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## 4. Moving tensors back to the CPU

In [13]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: ignored

In [14]:
# To fix the GPU tensor with Numpy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [15]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')