# Tensor Basics

In PyTorch, a tensor is a fundamental data structure that represents multi-dimensional arrays. Tensors are similar to NumPy arrays but come with additional capabilities, especially when it comes to GPU acceleration and automatic differentiation for building and training neural networks.

Tensors can have different dimensions, similar to arrays or matrices, but they can also have additional dimensions. Here are a few examples of tensors and their corresponding dimensions:

* 1D Tensor: Similar to a vector.
* 2D Tensor: Similar to a matrix.
* 3D Tensor: Often used to represent sequences of matrices or images with multiple channels (height, width, channel).
* 4D Tensor: Used for batched images (batch size, channel, height, width) or sequences of 3D tensors.
* 5D Tensor and beyond: Used for more complex data structures.

Tensors can hold data of various data types, such as float, integer, and more. They can also be moved between the CPU and GPU for efficient computation, which is particularly important when working with deep learning models.

In [5]:
import torch

# Empty tensor Returns a tensor filled with uninitialized data. The shape of the tensor is defined by the variable argument size.
x = torch.empty(1)
print(x)
y = torch.empty(2,2)
print(y)
print(y.dtype)

tensor([6.7593e-31])
tensor([[4.0553e-34, 3.3408e-41],
        [5.1957e+07, 3.3408e-41]])
torch.float32


In [6]:
y = torch.empty(2,2, dtype=torch.int64)
print(y)
print(y.dtype)

tensor([[135996357344624, 135996357344624],
        [              1, 102396449965632]])
torch.int64


In [7]:
x = torch.ones(3,3,dtype=torch.int64)
print(x,x.dtype,x.size())

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]) torch.int64 torch.Size([3, 3])


# torch.tensor
A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.

In [8]:
x = torch.tensor([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(x,x.dtype,x.size())

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) torch.int64 torch.Size([3, 3])


In [9]:
y = torch.tensor([[1., -1.], [1., -1.]])
print(y,y.dtype,y.size())

tensor([[ 1., -1.],
        [ 1., -1.]]) torch.float32 torch.Size([2, 2])


# torch.rand
Returns a tensor filled with random numbers from a uniform distribution on the interval [0,1). The shape of the tensor is defined by the variable argument size.

In [10]:
torch.rand(4)

tensor([0.2395, 0.7307, 0.5425, 0.3977])

In [11]:
r = torch.rand(2, 3)
print(r,r.dtype,r.size())

tensor([[0.8166, 0.2079, 0.5164],
        [0.9270, 0.5086, 0.7698]]) torch.float32 torch.Size([2, 3])


# torch.add
**torch.add(input, other, *, alpha=1, out=None) → Tensor**

Adds other, scaled by alpha, to input.

out = input + alpha x other


In [12]:
x = torch.rand(2,2)
y = torch.rand(2,2)
z = torch.add(x,y)
print(x)
print(y)
print(z)

tensor([[0.7062, 0.8830],
        [0.9790, 0.2462]])
tensor([[0.1946, 0.8576],
        [0.6507, 0.6009]])
tensor([[0.9008, 1.7406],
        [1.6297, 0.8471]])


# torch.sub
**torch.sub(input, other, *, alpha=1, out=None) → Tensor**

out = input - alpha x other

In [13]:
a = torch.tensor((1, 2))
b = torch.tensor((0, 1))
torch.sub(a, b)

tensor([1, 1])

# torch.mul
**torch.mul(input, other, *, out=None) → Tensor**

outi = inputi x otheri

In [14]:
a = torch.randn(3)
print(a)
torch.mul(a, 100)

tensor([-1.6904,  0.7160, -0.7370])


tensor([-169.0403,   71.6046,  -73.6981])

In [15]:
b = torch.randn(4, 1)
print(b)
c = torch.randn(1, 4)
print(c)
torch.mul(b, c)

tensor([[ 0.2178],
        [ 1.7567],
        [-2.1379],
        [-0.8200]])
tensor([[ 0.0477,  0.6900,  0.6302, -2.0508]])


tensor([[ 0.0104,  0.1503,  0.1372, -0.4466],
        [ 0.0838,  1.2121,  1.1071, -3.6027],
        [-0.1020, -1.4751, -1.3473,  4.3844],
        [-0.0391, -0.5658, -0.5168,  1.6817]])

In [16]:
a = torch.tensor([[2,6],
                  [1,9]])
b = torch.tensor([[1,2],
                  [1,9]])

print(a,a.size())
print(b,b.size())

c = torch.mul(a,b)
print(c)

tensor([[2, 6],
        [1, 9]]) torch.Size([2, 2])
tensor([[1, 2],
        [1, 9]]) torch.Size([2, 2])
tensor([[ 2, 12],
        [ 1, 81]])


# torch.div
**torch.div(input, other, *, rounding_mode=None, out=None) → Tensor**

outi = inputi / otheri

In [17]:
a = torch.tensor([[2,6],
                  [1,9]])
b = torch.tensor([[1,2],
                  [1,9]])

print(a,a.size())
print(b,b.size())

c = torch.div(a,b)
print(c)

tensor([[2, 6],
        [1, 9]]) torch.Size([2, 2])
tensor([[1, 2],
        [1, 9]]) torch.Size([2, 2])
tensor([[2., 3.],
        [1., 1.]])


# Tensor slicing

In [18]:
x = torch.tensor([[1,2,3,],
                 [4,5,6],
                 [7,8,9]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [19]:
# print(x[:1])
print(x[1:2])

tensor([[4, 5, 6]])


# Numpy and Tensor

In [20]:
import torch
import numpy as np

a = torch.ones(5)
print(a,type(a))
b = a.numpy()
print(b,type(b))

tensor([1., 1., 1., 1., 1.]) <class 'torch.Tensor'>
[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>


In [21]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [22]:
if torch.cuda.is_available():
  device = torch.device("cuda")
  x = torch.ones(5,device=device)
  b = a.numpy() #AttributeError: 'numpy.ndarray' object has no attribute 'numpy'
  print(b,type(b))

AttributeError: ignored

In [24]:
y = torch.ones(5)
y = y.to(device)
z = x+y
z

tensor([2., 2., 2., 2., 2.], device='cuda:0')

In [26]:
z = z.to('cpu')
z

tensor([2., 2., 2., 2., 2.])

In [27]:
new = z.numpy()
print(new,type(new))

[2. 2. 2. 2. 2.] <class 'numpy.ndarray'>
