# TORCH.AUTOGRAD

torch.autograd is PyTorch’s automatic differentiation engine that powers neural network training. In this section, you will get a conceptual understanding of how autograd helps a neural network train.

In [ ]:
import torch

x = torch.randn(3, requires_grad=True)
print(x)

y = x+2 # Do an operation with x tensor
print(y)
z = 2*y*y # Another operation with y tensor
z = z.mean()
print(z)

tensor([ 0.2282, -0.4150, -1.6290], requires_grad=True)
tensor([2.2282, 1.5850, 0.3710], grad_fn=<AddBackward0>)
tensor(5.0764, grad_fn=<MeanBackward0>)


In [ ]:
# Calculate Gradient
z.backward() # dz/dx
print(x.grad)

tensor([2.9709, 2.1133, 0.4947])


In [ ]:
import torch

weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
  model_output = (weights*3).sum()
  model_output.backward()
  print(weights.grad)
  weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
